- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - ec2_ami:
        region: us-west-2
        instance_id: "{{ instance_id }}"
        wait: no
        name: tensorflow_ami
      register: tf_ami

    - debug: var=tf_ami